version: '3.7'

services:
  guacd:
    container_name: guacd
    image: guacamole/guacamole:1.5.5 # Using specific version
    restart: unless-stopped
    # 'volumes:' section intentionally removed for guacd
    networks:
      - guacamole_net

  postgres:
    container_name: guacamole_db
    image: postgres:13 # Use a specific supported version
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: guacamole_db
      # !!! Password set by user !!!
      POSTGRES_PASSWORD: Rt@wqPP7ZvUgtS7
      POSTGRES_USER: guacamole_user
    networks:
      - guacamole_net

  guacamole:
    container_name: guacamole_web
    image: guacamole/guacamole:1.5.5 # Using specific version
    restart: unless-stopped
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: Rt@wqPP7ZvUgtS7 # Matches password above
      # GUACAMOLE_HOME: /home/guacamole/.guacamole # Only needed if using guacamole.properties
    ports: # <<<---- Port 8080 mapping included ---->>>
      - "8080:8080" # Map host port 8080 to container port 8080
    # volumes: # Only needed if installing extensions / using guacamole.properties
      # - ./guacamole_extensions:/home/guacamole/.guacamole/extensions
      # - ./guacamole_lib:/home/guacamole/.guacamole/lib
      # - ./guacamole.properties:/home/guacamole/.guacamole/guacamole.properties
    networks:
      - guacamole_net

  caddy:
    container_name: caddy_proxy
    image: caddy:latest
    restart: unless-stopped
    depends_on:
      - guacamole
    ports:
      # Map host ports 80 and 443 for Caddy
      - "80:80"
      - "443:443"
    volumes:
      # Mount the Caddy configuration file
      - ./Caddyfile:/etc/caddy/Caddyfile
      # Mount volumes for persistent Caddy data (certificates) and config
      - ./caddy_data:/data
      - ./caddy_config:/config
    networks:
      - guacamole_net # Connect Caddy to the same network

volumes:
  postgres-data:
  caddy_data:     # Persists Caddy's state including certificates
  caddy_config:   # Persists Caddy's configuration backups

networks:
  guacamole_net:
    driver: bridge